apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  selector:
    app: devops-app
  type: LoadBalancer  # This tells AWS to create an Elastic Load Balancer
  ports:
  - protocol: TCP
    port: 80         # The port the public will access
    targetPort: 3000 # The port your container is running on